CREATE TABLE users (
                       id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE children (
                          id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name    VARCHAR(255) NOT NULL,
                          user_id BIGINT NOT NULL,
                          CONSTRAINT children_user_id_fkey
                              FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE events (
                        id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name     VARCHAR(255) NOT NULL,
                        start_at TIMESTAMPTZ NOT NULL,
                        end_at   TIMESTAMPTZ NOT NULL,
                        repeat   BIGINT NOT NULL DEFAULT 0,
                        child_id BIGINT NOT NULL,
                        CONSTRAINT events_child_id_fkey
                            FOREIGN KEY (child_id) REFERENCES children(id) ON DELETE CASCADE
);

CREATE INDEX idx_children_user_id ON children(user_id);
CREATE INDEX idx_events_child_id  ON events(child_id);